baseurl = "/"
languageCode = "en-us"
title = "A minimal Hugo website"
#theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[module]
  [[module.imports]]
    path = "github.com/ianmadd/other-source"

    [[module.imports.mounts]]
    source = "content/"
    target = "content/"
